// @vitest-environment node
// Node environment: payload.login signs a JWT with jose, and jspdf's node build — both reject jsdom.
import { getPayload, Payload } from 'payload'
import config from '@/payload.config'

import { describe, it, beforeAll, afterAll, beforeEach, expect, vi } from 'vitest'

// S3 and the queue are the two things the tests don't talk to — everything else (routes, access,
// loaders, renderers, processors) runs for real against the test database.
vi.mock('@/lib/exports/storage', () => ({
  exportFileKey: (id: number | string, fileName: string) => `exports/${id}-random/${fileName}`,
  uploadExportFile: vi.fn(async () => undefined),
  presignExportDownload: vi.fn(async (key: string) => `https://s3.test/${key}?signed`),
  deleteExportFiles: vi.fn(async () => undefined),
}))
vi.mock('@/lib/queue/queues', async (importOriginal) => ({
  ...(await importOriginal<typeof import('@/lib/queue/queues')>()),
  enqueueGenerateExport: vi.fn(async () => undefined),
  enqueueExportReady: vi.fn(async () => undefined),
  enqueueEmail: vi.fn(async () => undefined),
}))

import { POST } from '@/app/api/exports/route'
import { GET as getStatus } from '@/app/api/exports/[id]/route'
import { GET as download } from '@/app/api/exports/[id]/download/route'
import { deleteExportFiles, uploadExportFile } from '@/lib/exports/storage'
import { enqueueExportReady, enqueueGenerateExport } from '@/lib/queue/queues'

import { processCleanupExportsJob } from '../../worker/src/processors/cleanup-exports.processor'
import { processExportReadyJob } from '../../worker/src/processors/export-ready.processor'
import { processGenerateExportJob } from '../../worker/src/processors/generate-export.processor'

let payload: Payload

const STAMP = Date.now()
const DAY = 24 * 60 * 60 * 1000

type TestUser = { id: number; email: string }

describe('Exports generated by the worker', () => {
  let muni: { id: number }
  let otherMuni: { id: number }
  let cat: { id: number }
  let admin: TestUser
  let organizer: TestUser
  let stranger: TestUser
  let organizationId: number
  const eventIds: number[] = []
  const relId = (value: number | { id: number }) => (typeof value === 'object' ? value.id : value)

  const authHeaders = async (user: TestUser | null): Promise<Record<string, string>> => {
    if (!user) return {}
    const { token } = await payload.login({ collection: 'users', data: { email: user.email, password: 'test1234' } })
    return { Authorization: `JWT ${token}` }
  }

  const requestExport = async (user: TestUser | null, body: unknown) =>
    POST(
      new Request('http://localhost/api/exports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(await authHeaders(user)) },
        body: JSON.stringify(body),
      }),
    )

  const statusAs = async (user: TestUser, id: number) =>
    getStatus(new Request(`http://localhost/api/exports/${id}`, { headers: await authHeaders(user) }), {
      params: Promise.resolve({ id: String(id) }),
    })

  const downloadAs = async (user: TestUser, id: number) =>
    download(new Request(`http://localhost/api/exports/${id}/download`, { headers: await authHeaders(user) }), {
      params: Promise.resolve({ id: String(id) }),
    })

  const createExportRow = (owner: TestUser, data: Record<string, unknown> = {}) =>
    payload.create({
      collection: 'exports',
      data: {
        owner: owner.id,
        kind: 'community-report',
        format: 'pdf',
        params: { municipalityId: String(muni.id), scope: 'all' },
        status: 'queued',
        expiresAt: new Date(Date.now() + 7 * DAY).toISOString(),
        ...data,
      },
      overrideAccess: true,
    })

  const uploadedBody = () => {
    const calls = vi.mocked(uploadExportFile).mock.calls
    return calls[calls.length - 1][1] as Buffer
  }

  beforeAll(async () => {
    payload = await getPayload({ config: await config })

    muni = await payload.create({
      collection: 'municipalities',
      data: { name: `Test Export Muni ${STAMP}`, rulesForCreation: 'approved_organizers', lat: 49.5661, lng: 15.9403 },
      overrideAccess: true,
    })
    otherMuni = await payload.create({
      collection: 'municipalities',
      data: { name: `Test Export Other ${STAMP}`, rulesForCreation: 'approved_organizers', lat: 49.5661, lng: 15.9403 },
      overrideAccess: true,
    })
    cat = await payload.create({
      collection: 'event-categories',
      data: { name: `Test Category Export ${STAMP}` },
      overrideAccess: true,
    })

    const makeUser = async (name: string, role: string, municipality: number) => {
      const user = await payload.create({
        collection: 'users',
        data: { email: `export-${name}-${STAMP}@test.local`, password: 'test1234', role: 'user' },
        overrideAccess: true,
      })
      await payload.create({
        collection: 'profiles',
        data: { user: user.id, fullName: `export ${name}`, municipality, notifyEmail: false },
        overrideAccess: true,
      })
      await payload.create({
        collection: 'user-roles',
        data: { user: user.id, municipality, role: role as 'organizer' },
        overrideAccess: true,
      })
      return user
    }
    admin = await makeUser('admin', 'municipality_admin', muni.id)
    organizer = await makeUser('spolek', 'organizer', muni.id)
    stranger = await makeUser('cizi', 'municipality_admin', otherMuni.id)

    const orgs = await payload.find({
      collection: 'organizations',
      where: { owner: { equals: organizer.id } },
      depth: 0,
      overrideAccess: true,
    })
    organizationId = orgs.docs[0].id

    // A Czech title on purpose — the PDF has to carry it with the embedded font.
    const event = await payload.create({
      collection: 'events',
      data: {
        title: `Žluťoučký kůň úpěl ${STAMP}`,
        dateTime: new Date(Date.now() + 3 * DAY).toISOString(),
        locationText: 'Náves',
        lat: 49.5661,
        lng: 15.9403,
        capacity: 10,
        organizer: organizer.id,
        categories: [cat.id],
        municipality: muni.id,
        status: 'active',
        isPaid: false,
        registrationApprovalMode: 'manual',
      },
      overrideAccess: true,
    })
    eventIds.push(event.id)
  })

  afterAll(async () => {
    const userIds = [admin.id, organizer.id, stranger.id]
    await payload.delete({ collection: 'exports', where: { owner: { in: userIds } }, overrideAccess: true }).catch(() => {})
    await payload.delete({ collection: 'events', where: { id: { in: eventIds } }, overrideAccess: true }).catch(() => {})
    await payload.delete({ collection: 'organizations', where: { owner: { in: userIds } }, overrideAccess: true }).catch(() => {})
    await payload.delete({ collection: 'event-categories', id: cat.id, overrideAccess: true }).catch(() => {})
    await payload.delete({ collection: 'notifications', where: { user: { in: userIds } }, overrideAccess: true }).catch(() => {})
    await payload.delete({ collection: 'profiles', where: { user: { in: userIds } }, overrideAccess: true }).catch(() => {})
    await payload.delete({ collection: 'user-roles', where: { user: { in: userIds } }, overrideAccess: true }).catch(() => {})
    await payload.delete({ collection: 'users', where: { id: { in: userIds } }, overrideAccess: true }).catch(() => {})
    for (const id of [muni.id, otherMuni.id]) {
      await payload.delete({ collection: 'municipalities', id, overrideAccess: true }).catch(() => {})
    }
  })

  beforeEach(async () => {
    vi.clearAllMocks()
    // The per-user "3 in flight" cap would otherwise trip on rows left by earlier tests.
    await payload.delete({
      collection: 'exports',
      where: { owner: { in: [admin.id, organizer.id, stranger.id] } },
      overrideAccess: true,
    })
  })

  describe('POST /api/exports', () => {
    it("queues a report of the admin's own obec", async () => {
      const response = await requestExport(admin, {
        kind: 'community-report',
        format: 'docx',
        params: { municipalityId: muni.id },
      })
      expect(response.status).toBe(200)
      const { id } = await response.json()

      const record = await payload.findByID({ collection: 'exports', id, depth: 0, overrideAccess: true })
      expect(record).toMatchObject({ status: 'queued', kind: 'community-report', format: 'docx' })
      expect(record.params).toEqual({ municipalityId: String(muni.id), scope: 'all' })
      expect(relId(record.owner)).toBe(admin.id)
      expect(vi.mocked(enqueueGenerateExport)).toHaveBeenCalledWith(
        { exportId: id },
        expect.objectContaining({ jobId: `generate-export-${id}` }),
      )
    })

    it('refuses anonymous requests, nonsense and other people’s obce', async () => {
      const body = { kind: 'community-report', format: 'pdf', params: { municipalityId: muni.id } }
      expect((await requestExport(null, body)).status).toBe(401)
      expect((await requestExport(admin, { kind: 'community-report', format: 'csv', params: {} })).status).toBe(400)
      expect((await requestExport(stranger, body)).status).toBe(403)
      expect((await requestExport(organizer, body)).status).toBe(403)
      expect(vi.mocked(enqueueGenerateExport)).not.toHaveBeenCalled()
    })

    it("lets an organizer export their organization but answers 404 for one that doesn't exist", async () => {
      const own = await requestExport(organizer, { kind: 'organization-report', format: 'csv', params: { organizationId } })
      expect(own.status).toBe(200)
      const missing = await requestExport(organizer, {
        kind: 'organization-report',
        format: 'csv',
        params: { organizationId: 999999999 },
      })
      expect(missing.status).toBe(404)
    })

    it('caps how many exports one person can have in flight', async () => {
      const body = { kind: 'municipality-events', format: 'csv', params: { municipalityId: muni.id, period: '30' } }
      for (let i = 0; i < 3; i++) expect((await requestExport(admin, body)).status).toBe(200)
      expect((await requestExport(admin, body)).status).toBe(429)
    })
  })

  describe('status and download', () => {
    it("shows an export only to its owner — anyone else gets a 404, not a 403", async () => {
      const record = await createExportRow(admin)
      expect((await statusAs(admin, record.id)).status).toBe(200)
      expect(await (await statusAs(admin, record.id)).json()).toMatchObject({ id: record.id, status: 'queued' })
      expect((await statusAs(stranger, record.id)).status).toBe(404)
      expect((await downloadAs(stranger, record.id)).status).toBe(404)
    })

    it('answers 409 until the file is there, 410 once it has expired', async () => {
      const queued = await createExportRow(admin)
      expect((await downloadAs(admin, queued.id)).status).toBe(409)

      const expired = await createExportRow(admin, {
        status: 'done',
        fileKey: 'exports/x/report.pdf',
        fileName: 'report.pdf',
        expiresAt: new Date(Date.now() - DAY).toISOString(),
      })
      expect((await downloadAs(admin, expired.id)).status).toBe(410)
    })

    it('sends a browser to a page instead of a bare JSON error', async () => {
      const visit = async (user: TestUser | null, id: number) =>
        download(
          new Request(`http://localhost/api/exports/${id}/download`, {
            headers: { ...(await authHeaders(user)), Accept: 'text/html,application/xhtml+xml' },
          }),
          { params: Promise.resolve({ id: String(id) }) },
        )
      const expired = await createExportRow(admin, {
        status: 'done',
        fileKey: 'exports/x/report.pdf',
        fileName: 'report.pdf',
        expiresAt: new Date(Date.now() - DAY).toISOString(),
      })

      const signedOut = await visit(null, expired.id)
      expect(signedOut.status).toBe(302)
      expect(signedOut.headers.get('location')).toBe(
        `http://localhost/auth?redirect=${encodeURIComponent(`/api/exports/${expired.id}/download`)}`,
      )
      expect((await visit(admin, expired.id)).headers.get('location')).toBe('http://localhost/export-nedostupny?duvod=expired')
      expect((await visit(stranger, expired.id)).headers.get('location')).toBe('http://localhost/export-nedostupny?duvod=missing')
    })

    it('redirects to a presigned URL and remembers that the owner downloaded it', async () => {
      const record = await createExportRow(admin, { status: 'done', fileKey: 'exports/1/report.pdf', fileName: 'report.pdf' })
      const response = await downloadAs(admin, record.id)
      expect(response.status).toBe(302)
      expect(response.headers.get('location')).toBe('https://s3.test/exports/1/report.pdf?signed')

      const after = await payload.findByID({ collection: 'exports', id: record.id, depth: 0, overrideAccess: true })
      expect(after.downloadedAt).toBeTruthy()
    })
  })

  describe('generate-export job', () => {
    it('renders a DOCX community report, uploads it and marks the row done', async () => {
      const record = await createExportRow(admin, { format: 'docx' })
      const result = await processGenerateExportJob({ exportId: record.id }, { attemptsMade: 0 })
      expect(result.generated).toBe(true)

      expect(uploadedBody().subarray(0, 2).toString()).toBe('PK')
      const after = await payload.findByID({ collection: 'exports', id: record.id, depth: 0, overrideAccess: true })
      expect(after.status).toBe('done')
      expect(after.fileName).toMatch(/^report-Test-Export-Muni-\d+-.+\.docx$/)
      expect(after.fileKey).toBe(`exports/${record.id}-random/${after.fileName}`)
      expect(vi.mocked(enqueueExportReady)).toHaveBeenCalledWith(
        { exportId: record.id },
        expect.objectContaining({ jobId: `export-ready-${record.id}` }),
      )
    })

    it('embeds a font that can write Czech into the PDFs', async () => {
      const record = await createExportRow(organizer, {
        kind: 'organization-report',
        format: 'pdf',
        params: { organizationId: String(organizationId) },
      })
      await processGenerateExportJob({ exportId: record.id }, { attemptsMade: 0 })
      const pdf = uploadedBody()
      expect(pdf.subarray(0, 4).toString()).toBe('%PDF')
      expect(pdf.toString('latin1')).toContain('NotoSans')
    })

    it('writes the CSV with a BOM so Excel reads it as UTF-8', async () => {
      const record = await createExportRow(admin, {
        kind: 'municipality-events',
        format: 'csv',
        params: { municipalityId: String(muni.id), scope: 'all', period: '30' },
      })
      await processGenerateExportJob({ exportId: record.id }, { attemptsMade: 0 })
      const csv = uploadedBody().toString('utf8')
      expect(csv.charCodeAt(0)).toBe(0xfeff)
      expect(csv).toContain(`Žluťoučký kůň úpěl ${STAMP}`)
    })

    it('leaves the row alone on a retryable failure and fails it on the last attempt', async () => {
      vi.mocked(uploadExportFile).mockRejectedValue(new Error('S3 down'))
      const record = await createExportRow(admin)

      await expect(processGenerateExportJob({ exportId: record.id }, { attemptsMade: 0 })).rejects.toThrow('S3 down')
      let after = await payload.findByID({ collection: 'exports', id: record.id, depth: 0, overrideAccess: true })
      expect(after.status).toBe('processing')

      await expect(processGenerateExportJob({ exportId: record.id }, { attemptsMade: 2 })).rejects.toThrow('S3 down')
      after = await payload.findByID({ collection: 'exports', id: record.id, depth: 0, overrideAccess: true })
      expect(after).toMatchObject({ status: 'failed', error: 'S3 down' })
      vi.mocked(uploadExportFile).mockResolvedValue(undefined)
    })
  })

  describe('export-ready job', () => {
    const notificationsOf = (user: TestUser) =>
      payload.find({ collection: 'notifications', where: { user: { equals: user.id } }, depth: 0, overrideAccess: true })

    it('stays quiet when the owner already downloaded the file from the dialog', async () => {
      const record = await createExportRow(admin, {
        status: 'done',
        fileKey: 'exports/1/a.pdf',
        fileName: 'a.pdf',
        downloadedAt: new Date().toISOString(),
      })
      expect(await processExportReadyJob({ exportId: record.id })).toMatchObject({ skipped: 'already_downloaded' })
    })

    it('notifies the owner with a link to the download route', async () => {
      const before = (await notificationsOf(organizer)).totalDocs
      const record = await createExportRow(organizer, { status: 'done', fileKey: 'exports/1/b.pdf', fileName: 'b.pdf' })
      expect(await processExportReadyJob({ exportId: record.id })).toEqual({ notified: true })

      const after = await notificationsOf(organizer)
      expect(after.totalDocs).toBe(before + 1)
      expect(after.docs.some((n) => n.link === `/api/exports/${record.id}/download`)).toBe(true)
    })
  })

  describe('cleanup-exports job', () => {
    it('drops expired exports with their files and keeps the rest', async () => {
      const expired = await createExportRow(admin, {
        status: 'done',
        fileKey: 'exports/old/report.pdf',
        fileName: 'report.pdf',
        expiresAt: new Date(Date.now() - DAY).toISOString(),
      })
      const fresh = await createExportRow(admin)

      const result = await processCleanupExportsJob()
      expect(result.deleted).toBeGreaterThanOrEqual(1)
      expect(vi.mocked(deleteExportFiles)).toHaveBeenCalledWith(expect.arrayContaining(['exports/old/report.pdf']))

      const remaining = await payload.find({
        collection: 'exports',
        where: { id: { in: [expired.id, fresh.id] } },
        depth: 0,
        overrideAccess: true,
      })
      expect(remaining.docs.map((d) => d.id)).toEqual([fresh.id])
    })
  })
})
