/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    municipalities: Municipality;
    'event-categories': EventCategory;
    profiles: Profile;
    'user-roles': UserRole;
    events: Event;
    registrations: Registration;
    'event-media': EventMedia;
    'event-feedback': EventFeedback;
    'organizer-requests': OrganizerRequest;
    'organizer-payouts': OrganizerPayout;
    'auth-identities': AuthIdentity;
    'municipality-areas': MunicipalityArea;
    consents: Consent;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    municipalities: MunicipalitiesSelect<false> | MunicipalitiesSelect<true>;
    'event-categories': EventCategoriesSelect<false> | EventCategoriesSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'user-roles': UserRolesSelect<false> | UserRolesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'event-media': EventMediaSelect<false> | EventMediaSelect<true>;
    'event-feedback': EventFeedbackSelect<false> | EventFeedbackSelect<true>;
    'organizer-requests': OrganizerRequestsSelect<false> | OrganizerRequestsSelect<true>;
    'organizer-payouts': OrganizerPayoutsSelect<false> | OrganizerPayoutsSelect<true>;
    'auth-identities': AuthIdentitiesSelect<false> | AuthIdentitiesSelect<true>;
    'municipality-areas': MunicipalityAreasSelect<false> | MunicipalityAreasSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Platform-level role — controls Payload admin access, not community roles.
   */
  role: 'admin' | 'user';
  tenants?:
    | {
        tenant: number | Municipality;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipalities".
 */
export interface Municipality {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Who is allowed to create events in this municipality.
   */
  rulesForCreation: 'anyone' | 'approved_organizers' | 'municipality_only';
  /**
   * The user who administers this municipality.
   */
  adminUser?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories".
 */
export interface EventCategory {
  id: number;
  /**
   * e.g. Kultura, Příroda, Vzdělávání
   */
  name: string;
  /**
   * Icon identifier used by the frontend (e.g. a lucide-react icon name).
   */
  icon?: string | null;
  /**
   * Color used to render this category in the app (hex or design token).
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  /**
   * 1:1 link to the account this profile belongs to.
   */
  user: number | User;
  fullName: string;
  /**
   * The user's home municipality.
   */
  municipality: number | Municipality;
  /**
   * Organizer payout account. Only visible/editable by the profile owner.
   */
  payoutIban?: string | null;
  phone?: string | null;
  dateOfBirth?: string | null;
  gender?: ('zena' | 'muz' | 'jine' | 'neuvedeno') | null;
  interests?: (number | EventCategory)[] | null;
  /**
   * Neighborhood within the municipality, chosen during onboarding.
   */
  homeArea?: (number | null) | MunicipalityArea;
  onboardingCompleted?: boolean | null;
  isVolunteer?: boolean | null;
  volunteerFocus?: string[] | null;
  volunteerNote?: string | null;
  volunteerSince?: string | null;
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Neighborhoods within a municipality, used for the onboarding "where do you live" map.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipality-areas".
 */
export interface MunicipalityArea {
  id: number;
  municipality: number | Municipality;
  name: string;
  /**
   * Short slug-like identifier, unique within the municipality.
   */
  code: string;
  centerLat: number;
  centerLng: number;
  radiusM: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles".
 */
export interface UserRole {
  id: number;
  user: number | User;
  /**
   * The municipality this role applies to.
   */
  municipality: number | Municipality;
  /**
   * Enum matches ERD §0.2 pilot roles. "prescriber" is a reserved slot for the intervention layer — not wired to any workflow yet (see brief §B).
   */
  role: 'participant' | 'organizer' | 'municipality_admin' | 'prescriber';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: string | null;
  municipality: number | Municipality;
  dateTime: string;
  locationText: string;
  lat?: number | null;
  lng?: number | null;
  capacity: number;
  /**
   * The user organizing this event.
   */
  organizer: number | User;
  status: 'active' | 'full' | 'finished' | 'cancelled';
  category: number | EventCategory;
  /**
   * Cover image shown in event listings.
   */
  image?: (number | null) | Media;
  /**
   * Tagged by the organizer at creation — feeds the Datavita "share of volunteers" metric.
   */
  isVolunteering?: boolean | null;
  isPaid?: boolean | null;
  /**
   * Price in the smallest currency unit (e.g. haléře), used with Stripe.
   */
  priceCents?: number | null;
  cancellationPolicy: 'none' | 'cancel_24h' | 'cancel_48h' | 'cancel_7d';
  /**
   * Soft-delete marker — preserves attendance history when an event is removed.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  event: number | Event;
  user: number | User;
  /**
   * "Smí přijít" — whether the registration itself is allowed, not whether they attended.
   */
  status: 'pending_payment' | 'pending' | 'approved' | 'rejected' | 'cancelled';
  /**
   * What actually happened — set by the organizer after the event, on the manage-event page.
   */
  attendanceStatus?: ('not_marked' | 'attended' | 'no_show' | 'excused') | null;
  attendanceMarkedAt?: string | null;
  /**
   * The organizer who marked attendance.
   */
  attendanceMarkedBy?: (number | null) | User;
  attendanceNote?: string | null;
  paymentStatus: 'none' | 'paid' | 'refunded' | 'failed';
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  amountPaidCents?: number | null;
  refundedAt?: string | null;
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-media".
 */
export interface EventMedia {
  id: number;
  event: number | Event;
  media: number | Media;
  uploadedBy: number | User;
  visibility: 'private' | 'municipality' | 'public';
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-feedback".
 */
export interface EventFeedback {
  id: number;
  /**
   * One feedback entry per attended registration.
   */
  registration: number | Registration;
  satisfactionRating: number;
  /**
   * Did you feel welcome?
   */
  feltWelcomeRating?: number | null;
  /**
   * Did you meet someone new?
   */
  metSomeoneNew?: boolean | null;
  /**
   * Did you come alone?
   */
  cameAlone?: boolean | null;
  comment?: string | null;
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizer-requests".
 */
export interface OrganizerRequest {
  id: number;
  user: number | User;
  municipality: number | Municipality;
  /**
   * Approving a request should create a matching User Role of "organizer".
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Note from the requester about why they want to organize events.
   */
  description: string;
  decidedAt?: string | null;
  decidedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizer-payouts".
 */
export interface OrganizerPayout {
  id: number;
  profile: number | Profile;
  amountCents: number;
  currency: string;
  status: 'pending' | 'processing' | 'paid' | 'failed';
  /**
   * Stripe transfer ID once the payout has been sent.
   */
  stripeTransferId?: string | null;
  periodStart?: string | null;
  periodEnd?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-identities".
 */
export interface AuthIdentity {
  id: number;
  user: number | User;
  /**
   * The Auth0 "sub" claim, e.g. auth0|abc123 or google-oauth2|123.
   */
  providerSubject: string;
  provider: string;
  connection?: string | null;
  /**
   * database | social
   */
  providerType?: string | null;
  email?: string | null;
  emailVerified?: boolean | null;
  lastLoginAt?: string | null;
  lastSyncedAt?: string | null;
  /**
   * Raw Auth0 session.user payload, cached for reference.
   */
  profile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only consent log — GDPR foundation (brief A3). Existing rows are never edited except revokedAt; a changed policy version is a new row, not an update.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  user: number | User;
  /**
   * Schema allows more types later (wellbeing_measurement, media_publication…) without a migration — see ERD §2.4.
   */
  type: 'platform_terms' | 'marketing';
  /**
   * Version of the consent text the user agreed to, e.g. "1.0".
   */
  version: string;
  grantedAt: string;
  /**
   * Revoking does not delete the row or any participation history it relates to.
   */
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only. Written by server-side hooks (overrideAccess) on sensitive changes — role grants, consent revocation, organizer-request decisions. Not writable or deletable through the API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  /**
   * e.g. "user-roles.grant", "consents.revoke", "organizer-requests.decide".
   */
  action: string;
  /**
   * Who performed the action. Empty for system-triggered entries.
   */
  actor?: (number | null) | User;
  targetCollection: string;
  targetId: string;
  municipality?: (number | null) | Municipality;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'municipalities';
        value: number | Municipality;
      } | null)
    | ({
        relationTo: 'event-categories';
        value: number | EventCategory;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'user-roles';
        value: number | UserRole;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'event-media';
        value: number | EventMedia;
      } | null)
    | ({
        relationTo: 'event-feedback';
        value: number | EventFeedback;
      } | null)
    | ({
        relationTo: 'organizer-requests';
        value: number | OrganizerRequest;
      } | null)
    | ({
        relationTo: 'organizer-payouts';
        value: number | OrganizerPayout;
      } | null)
    | ({
        relationTo: 'auth-identities';
        value: number | AuthIdentity;
      } | null)
    | ({
        relationTo: 'municipality-areas';
        value: number | MunicipalityArea;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipalities_select".
 */
export interface MunicipalitiesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  rulesForCreation?: T;
  adminUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories_select".
 */
export interface EventCategoriesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  user?: T;
  fullName?: T;
  municipality?: T;
  payoutIban?: T;
  phone?: T;
  dateOfBirth?: T;
  gender?: T;
  interests?: T;
  homeArea?: T;
  onboardingCompleted?: T;
  isVolunteer?: T;
  volunteerFocus?: T;
  volunteerNote?: T;
  volunteerSince?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles_select".
 */
export interface UserRolesSelect<T extends boolean = true> {
  user?: T;
  municipality?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  municipality?: T;
  dateTime?: T;
  locationText?: T;
  lat?: T;
  lng?: T;
  capacity?: T;
  organizer?: T;
  status?: T;
  category?: T;
  image?: T;
  isVolunteering?: T;
  isPaid?: T;
  priceCents?: T;
  cancellationPolicy?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  status?: T;
  attendanceStatus?: T;
  attendanceMarkedAt?: T;
  attendanceMarkedBy?: T;
  attendanceNote?: T;
  paymentStatus?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  amountPaidCents?: T;
  refundedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-media_select".
 */
export interface EventMediaSelect<T extends boolean = true> {
  event?: T;
  media?: T;
  uploadedBy?: T;
  visibility?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-feedback_select".
 */
export interface EventFeedbackSelect<T extends boolean = true> {
  registration?: T;
  satisfactionRating?: T;
  feltWelcomeRating?: T;
  metSomeoneNew?: T;
  cameAlone?: T;
  comment?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizer-requests_select".
 */
export interface OrganizerRequestsSelect<T extends boolean = true> {
  user?: T;
  municipality?: T;
  status?: T;
  description?: T;
  decidedAt?: T;
  decidedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizer-payouts_select".
 */
export interface OrganizerPayoutsSelect<T extends boolean = true> {
  profile?: T;
  amountCents?: T;
  currency?: T;
  status?: T;
  stripeTransferId?: T;
  periodStart?: T;
  periodEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-identities_select".
 */
export interface AuthIdentitiesSelect<T extends boolean = true> {
  user?: T;
  providerSubject?: T;
  provider?: T;
  connection?: T;
  providerType?: T;
  email?: T;
  emailVerified?: T;
  lastLoginAt?: T;
  lastSyncedAt?: T;
  profile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipality-areas_select".
 */
export interface MunicipalityAreasSelect<T extends boolean = true> {
  municipality?: T;
  name?: T;
  code?: T;
  centerLat?: T;
  centerLng?: T;
  radiusM?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  version?: T;
  grantedAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  actor?: T;
  targetCollection?: T;
  targetId?: T;
  municipality?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}