/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    municipalities: Municipality;
    'event-categories': EventCategory;
    profiles: Profile;
    'user-roles': UserRole;
    events: Event;
    registrations: Registration;
    'event-media': EventMedia;
    'event-feedback': EventFeedback;
    'auth-identities': AuthIdentity;
    'municipality-areas': MunicipalityArea;
    consents: Consent;
    'audit-log': AuditLog;
    notifications: Notification;
    organizations: Organization;
    'organizer-requests': OrganizerRequest;
    'volunteer-flag-requests': VolunteerFlagRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    municipalities: MunicipalitiesSelect<false> | MunicipalitiesSelect<true>;
    'event-categories': EventCategoriesSelect<false> | EventCategoriesSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'user-roles': UserRolesSelect<false> | UserRolesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'event-media': EventMediaSelect<false> | EventMediaSelect<true>;
    'event-feedback': EventFeedbackSelect<false> | EventFeedbackSelect<true>;
    'auth-identities': AuthIdentitiesSelect<false> | AuthIdentitiesSelect<true>;
    'municipality-areas': MunicipalityAreasSelect<false> | MunicipalityAreasSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'organizer-requests': OrganizerRequestsSelect<false> | OrganizerRequestsSelect<true>;
    'volunteer-flag-requests': VolunteerFlagRequestsSelect<false> | VolunteerFlagRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Platform-level role — controls Payload admin access, not community roles.
   */
  role: 'admin' | 'user';
  tenants?:
    | {
        tenant: number | Municipality;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipalities".
 */
export interface Municipality {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Brief §4 "poloha je mandatory field" — plots this obec on the municipality-switcher map (brief §4/§7 "mapka jako v Projects/eduard-app").
   */
  lat: number;
  lng: number;
  /**
   * The user who administers this municipality. Kept in sync with "municipality_admin" user-roles (the most recently granted one).
   */
  adminUser?: (number | null) | User;
  /**
   * Maximální vzdálenost (km) mezi středem obce (lat/lng výše) a místem konání akce. Akce mimo tento okruh nejde založit ani upravit — brání přiřazení akce z jiného města k této obci.
   */
  eventRadiusKm: number;
  /**
   * Brief §3 "Pravidla pro vznik akcí" — controls who may create events for this municipality (see Events.access.create). A signed-out visitor is always read-only regardless of this setting.
   */
  rulesForCreation: 'municipality_only' | 'anyone' | 'approved_organizers';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories".
 */
export interface EventCategory {
  id: number;
  /**
   * e.g. Kultura, Příroda, Vzdělávání
   */
  name: string;
  /**
   * Icon identifier used by the frontend (e.g. a lucide-react icon name).
   */
  icon?: string | null;
  /**
   * Color used to render this category in the app (hex or design token).
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  /**
   * 1:1 link to the account this profile belongs to.
   */
  user: number | User;
  fullName: string;
  /**
   * The user's home municipality. Empty = "bez obce" (their town doesn't use Lonvita yet) — they browse and can register for events across every municipality.
   */
  municipality?: (number | null) | Municipality;
  phone?: string | null;
  /**
   * Brief §8 "přidání a ověření tel. čísla pro GoSMS" — set once an OTP sent to `phone` is confirmed.
   */
  phoneVerified?: boolean | null;
  /**
   * Brief §7 "Preferovaný kanál notifikací... e-mail defaultně."
   */
  notifyEmail?: boolean | null;
  /**
   * Brief §7 "...aplikace volitelně."
   */
  notifyInApp?: boolean | null;
  dateOfBirth?: string | null;
  gender?: ('zena' | 'muz' | 'jine' | 'neuvedeno') | null;
  interests?: (number | EventCategory)[] | null;
  /**
   * Neighborhood within the municipality, chosen during onboarding.
   */
  homeArea?: (number | null) | MunicipalityArea;
  onboardingCompleted?: boolean | null;
  isVolunteer?: boolean | null;
  volunteerFocus?: string[] | null;
  volunteerNote?: string | null;
  volunteerSince?: string | null;
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Neighborhoods within a municipality, used for the onboarding "where do you live" map.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipality-areas".
 */
export interface MunicipalityArea {
  id: number;
  municipality: number | Municipality;
  name: string;
  /**
   * Short slug-like identifier, unique within the municipality.
   */
  code: string;
  centerLat: number;
  centerLng: number;
  radiusM: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles".
 */
export interface UserRole {
  id: number;
  user: number | User;
  /**
   * The municipality this role applies to.
   */
  municipality: number | Municipality;
  /**
   * Enum matches ERD §0.2 pilot roles, plus "organizer" (brief §4). A user can hold the same role in several municipalities at once — organizers and volunteers aren't tied to one town (brief §8 "Působení jednoho člověka napříč víc obcemi"). "prescriber" is a reserved slot for the intervention layer — not wired to any workflow yet (see brief §B).
   */
  role: 'participant' | 'municipality_admin' | 'organizer' | 'prescriber';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: string | null;
  municipality: number | Municipality;
  dateTime: string;
  /**
   * Brief §4 "Datum jako rozsah" — an event can span more than one day. Leave empty for a single-day event.
   */
  endDateTime?: string | null;
  /**
   * Brief §4 "Opakující se série" (e.g. "weekly:tuesday") — a simple machine-readable rule set on the first occurrence only. Combines with endDateTime for a multi-day recurring series. Occurrence generation is a separate, later piece; this field just records the intent.
   */
  recurrenceRule?: string | null;
  /**
   * Set on a generated occurrence, pointing back at the event that defines recurrenceRule.
   */
  recurrenceParent?: (number | null) | Event;
  /**
   * Human-readable label for the picked location (from the map picker's search result, editable).
   */
  locationText: string;
  /**
   * Brief §12 "ROZHODNĚ NE NAPSAT LOKACI" — set via the map picker, never typed freehand.
   */
  lat: number;
  lng: number;
  /**
   * Brief §4/§6 "Tag přístupnosti místa konání" — set by the organizer, shown to participants on the event.
   */
  accessibilityTags?: ('wheelchair_access' | 'induction_loop' | 'seating' | 'accessible_wc')[] | null;
  capacity: number;
  /**
   * Brief §4 "Přihlašování účastníků" — chosen per event by the organizer. "auto" also gates the server-side capacity check on Registrations.
   */
  registrationApprovalMode: 'auto' | 'manual';
  /**
   * The user organizing this event. Additional organizers: see coOrganizers below.
   */
  organizer: number | User;
  /**
   * Brief §4 "Organizace" — which of the organizer's organizations this event is published under. Empty = published under their personal name.
   */
  organization?: (number | null) | Organization;
  /**
   * Brief §4 "Spolupořadatelství" — additional organizers (e.g. two organizations running an event together). The event appears in each co-organizer's own dashboard/"moje akce" alongside the primary organizer.
   */
  coOrganizers?: (number | User)[] | null;
  status: 'active' | 'full' | 'finished' | 'cancelled';
  /**
   * Brief §2 "Jedna akce může mít víc kategorií zároveň" — one or more categories. Filtering by a category matches any event that has it among its categories.
   */
  categories: (number | EventCategory)[];
  /**
   * Cover image shown in event listings.
   */
  image?: (number | null) | Media;
  /**
   * Tagged by the organizer at creation — feeds the Datavita "share of volunteers" metric.
   */
  isVolunteering?: boolean | null;
  isPaid?: boolean | null;
  /**
   * Price in the smallest currency unit (e.g. haléře). Informational only — the app does not process payment; the organizer handles it outside the app (brief §4).
   */
  priceCents?: number | null;
  cancellationPolicy: 'none' | 'cancel_24h' | 'cancel_48h' | 'cancel_7d';
  /**
   * Soft-delete marker — preserves attendance history when an event is removed.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  /**
   * Free text, no obec approval needed — the organizer manages their own list in their profile.
   */
  name: string;
  /**
   * The organizer who added this organization.
   */
  owner: number | User;
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  event: number | Event;
  user: number | User;
  /**
   * "Smí přijít" — whether the registration itself is allowed, not whether they attended.
   */
  status: 'pending' | 'approved' | 'rejected' | 'cancelled';
  /**
   * What actually happened — set by the organizer after the event, on the manage-event page.
   */
  attendanceStatus?: ('not_marked' | 'attended' | 'no_show' | 'excused') | null;
  attendanceMarkedAt?: string | null;
  /**
   * The organizer who marked attendance.
   */
  attendanceMarkedBy?: (number | null) | User;
  attendanceNote?: string | null;
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-media".
 */
export interface EventMedia {
  id: number;
  event: number | Event;
  media: number | Media;
  uploadedBy: number | User;
  visibility: 'private' | 'municipality' | 'public';
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-feedback".
 */
export interface EventFeedback {
  id: number;
  /**
   * One feedback entry per attended registration.
   */
  registration: number | Registration;
  satisfactionRating: number;
  /**
   * Did you feel welcome?
   */
  feltWelcomeRating?: number | null;
  /**
   * Did you meet someone new?
   */
  metSomeoneNew?: boolean | null;
  /**
   * Did you come alone?
   */
  cameAlone?: boolean | null;
  comment?: string | null;
  /**
   * Soft-delete marker — preserves history for reporting. Set by admin action, not user-facing delete.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-identities".
 */
export interface AuthIdentity {
  id: number;
  user: number | User;
  /**
   * The Auth0 "sub" claim, e.g. auth0|abc123 or google-oauth2|123.
   */
  providerSubject: string;
  provider: string;
  connection?: string | null;
  /**
   * database | social
   */
  providerType?: string | null;
  email?: string | null;
  emailVerified?: boolean | null;
  lastLoginAt?: string | null;
  lastSyncedAt?: string | null;
  /**
   * Raw Auth0 session.user payload, cached for reference.
   */
  profile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only consent log — GDPR foundation (brief A3). Existing rows are never edited except revokedAt; a changed policy version is a new row, not an update.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  user: number | User;
  /**
   * Schema allows more types later (wellbeing_measurement, media_publication…) without a migration — see ERD §2.4.
   */
  type: 'platform_terms' | 'marketing';
  /**
   * Version of the consent text the user agreed to, e.g. "1.0".
   */
  version: string;
  grantedAt: string;
  /**
   * Revoking does not delete the row or any participation history it relates to.
   */
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only. Written by server-side hooks (overrideAccess) on sensitive changes — role grants, consent revocation. Not writable or deletable through the API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  /**
   * e.g. "user-roles.grant", "consents.revoke".
   */
  action: string;
  /**
   * Who performed the action. Empty for system-triggered entries.
   */
  actor?: (number | null) | User;
  targetCollection: string;
  targetId: string;
  municipality?: (number | null) | Municipality;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-app notifications. Written by server-side hooks (overrideAccess), not user-created.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Recipient of this notification.
   */
  user: number | User;
  title: string;
  message: string;
  /**
   * In-app route opened when the notification is clicked, e.g. "/akce/12". Empty = not clickable.
   */
  link?: string | null;
  /**
   * Set when the recipient opens/dismisses the notification.
   */
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizer-requests".
 */
export interface OrganizerRequest {
  id: number;
  user: number | User;
  municipality: number | Municipality;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-flag-requests".
 */
export interface VolunteerFlagRequest {
  id: number;
  event: number | Event;
  requestedBy: number | User;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'municipalities';
        value: number | Municipality;
      } | null)
    | ({
        relationTo: 'event-categories';
        value: number | EventCategory;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'user-roles';
        value: number | UserRole;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'event-media';
        value: number | EventMedia;
      } | null)
    | ({
        relationTo: 'event-feedback';
        value: number | EventFeedback;
      } | null)
    | ({
        relationTo: 'auth-identities';
        value: number | AuthIdentity;
      } | null)
    | ({
        relationTo: 'municipality-areas';
        value: number | MunicipalityArea;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'organizer-requests';
        value: number | OrganizerRequest;
      } | null)
    | ({
        relationTo: 'volunteer-flag-requests';
        value: number | VolunteerFlagRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipalities_select".
 */
export interface MunicipalitiesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  lat?: T;
  lng?: T;
  adminUser?: T;
  eventRadiusKm?: T;
  rulesForCreation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories_select".
 */
export interface EventCategoriesSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  user?: T;
  fullName?: T;
  municipality?: T;
  phone?: T;
  phoneVerified?: T;
  notifyEmail?: T;
  notifyInApp?: T;
  dateOfBirth?: T;
  gender?: T;
  interests?: T;
  homeArea?: T;
  onboardingCompleted?: T;
  isVolunteer?: T;
  volunteerFocus?: T;
  volunteerNote?: T;
  volunteerSince?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles_select".
 */
export interface UserRolesSelect<T extends boolean = true> {
  user?: T;
  municipality?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  municipality?: T;
  dateTime?: T;
  endDateTime?: T;
  recurrenceRule?: T;
  recurrenceParent?: T;
  locationText?: T;
  lat?: T;
  lng?: T;
  accessibilityTags?: T;
  capacity?: T;
  registrationApprovalMode?: T;
  organizer?: T;
  organization?: T;
  coOrganizers?: T;
  status?: T;
  categories?: T;
  image?: T;
  isVolunteering?: T;
  isPaid?: T;
  priceCents?: T;
  cancellationPolicy?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  status?: T;
  attendanceStatus?: T;
  attendanceMarkedAt?: T;
  attendanceMarkedBy?: T;
  attendanceNote?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-media_select".
 */
export interface EventMediaSelect<T extends boolean = true> {
  event?: T;
  media?: T;
  uploadedBy?: T;
  visibility?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-feedback_select".
 */
export interface EventFeedbackSelect<T extends boolean = true> {
  registration?: T;
  satisfactionRating?: T;
  feltWelcomeRating?: T;
  metSomeoneNew?: T;
  cameAlone?: T;
  comment?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-identities_select".
 */
export interface AuthIdentitiesSelect<T extends boolean = true> {
  user?: T;
  providerSubject?: T;
  provider?: T;
  connection?: T;
  providerType?: T;
  email?: T;
  emailVerified?: T;
  lastLoginAt?: T;
  lastSyncedAt?: T;
  profile?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "municipality-areas_select".
 */
export interface MunicipalityAreasSelect<T extends boolean = true> {
  municipality?: T;
  name?: T;
  code?: T;
  centerLat?: T;
  centerLng?: T;
  radiusM?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  version?: T;
  grantedAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  actor?: T;
  targetCollection?: T;
  targetId?: T;
  municipality?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  message?: T;
  link?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizer-requests_select".
 */
export interface OrganizerRequestsSelect<T extends boolean = true> {
  user?: T;
  municipality?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-flag-requests_select".
 */
export interface VolunteerFlagRequestsSelect<T extends boolean = true> {
  event?: T;
  requestedBy?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}